#ifndef _DEFINE_H
#define _DEFINE_H

#define MAX_CONFIG_KEYS 1000
#define MAX_KEY_LENGTH 128
#define MAX_VALUE_LENGTH 512
#define INIT_NUMBER_STRUCT 10
#define NUMBER_STRUCT_INCREASE 2
#define PORT_DNS 53
#define ONE_BYTE 1
#define TWO_BYTE 2
#define FOUR_BYTE 4
#define EIGHT_BYTE 8
#define MAX_PATH_LENGTH 1024
#define MAX_IP_LENGTH 64
#define SLEEP_TIME_TO_RUN 6
#define IPSET_TIMEOUT 10000
#define MAX_LOG_SIZE 104857


extern char SRC_WEB_BLOCK_PATH[MAX_PATH_LENGTH];
extern char LOG_FILE_PATH[MAX_PATH_LENGTH];
extern char DOMAIN_NAME_TXT_PATH[MAX_PATH_LENGTH];
extern char DEFAULT_CONFIG_FILE[MAX_PATH_LENGTH];
extern char BLOCK_WEB_TXT_PATH[MAX_PATH_LENGTH];
extern char IP_DB_DIR[MAX_PATH_LENGTH];
extern char DOMAIN_DIR[MAX_PATH_LENGTH];

#endif